// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr4G7ONKuhh6S1eOdH5KNCVEntSunPgv0',
    appId: '1:1081031436445:web:da0c4ddcf2e98a69698c74',
    messagingSenderId: '1081031436445',
    projectId: 'sample-39ef7',
    authDomain: 'sample-39ef7.firebaseapp.com',
    storageBucket: 'sample-39ef7.appspot.com',
    measurementId: 'G-PNPMQEJKQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc7ZJf4MSqvhA3zgfJTUJTcj-lSE6QdME',
    appId: '1:1081031436445:android:6729862b3ee92451698c74',
    messagingSenderId: '1081031436445',
    projectId: 'sample-39ef7',
    storageBucket: 'sample-39ef7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZATuV_anfrTyXFNuPtQoFikTaGfiYR6o',
    appId: '1:1081031436445:ios:5f990a9fe8056574698c74',
    messagingSenderId: '1081031436445',
    projectId: 'sample-39ef7',
    storageBucket: 'sample-39ef7.appspot.com',
    iosClientId: '1081031436445-n53pgiepu9ea5kdr6d09fr4b6529btlb.apps.googleusercontent.com',
    iosBundleId: 'com.example.agilex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZATuV_anfrTyXFNuPtQoFikTaGfiYR6o',
    appId: '1:1081031436445:ios:5f990a9fe8056574698c74',
    messagingSenderId: '1081031436445',
    projectId: 'sample-39ef7',
    storageBucket: 'sample-39ef7.appspot.com',
    iosClientId: '1081031436445-n53pgiepu9ea5kdr6d09fr4b6529btlb.apps.googleusercontent.com',
    iosBundleId: 'com.example.agilex',
  );
}
